### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by amar-topalovic** [syvsto/booster2024_wasm_components#1]
### Global

- ~~[ ] List opp dependencies i starten av hver oppgave~~
- [x] Se på VENV og docker

### Task 1:

- [x] Kombinere branch /rewritesuggestions med master
- [x] Oppdatér byggescript for JS-biten så det tar med alle dependencies og støtter stdout.

### Task 2:

- [x] Definer command component
- [x] Ha ferdig løst intermediate components
- [x] Få oppgaveløser til å fylle ut .wit
- [x] Forklare hva starter er for noe og hvor det skal brukes

### Task 3:

- [x] Leveres med ferdig rust-kode (utenom wasm_bindgen-biten)
- [x]  Oppgave blir å fylle ut tilhørende .wit basert på innholdet i lib.rs
- [x] Når de skal virtualisere rust-komponenten nevne wasi-virt: "..ved hjelp av wasi-virt virtualiser komponenten.."
- [x] Python-biten: oppgaveløser modifiserer clustering.wit
- [x] Beskriv poller.py - trengs for proxy-world, ingenting for bruker å gjøre her
- [x]  reorgranisere wit foldere for python

### Task 4:

- [x] Sette opp wasm_bindgen-kode
- [ ] Float64-array i script.js
- [x] 2 nivåer lenger opp når referere til pkg i vite.config.js (`"file:../../../../03/clustering-rs/pkg/"`)
- [x] Ferdigskrevet vite.config.js
- [x] Linking

### Task5:

- [x] Logging -> Legg til timestamp i response f.eks
- [x] Bonus: Persistence (sjekk ut spin kv/database)

**Comment by amar-topalovic** [comment]
![image](https://github.com/syvsto/booster2024_wasm_components/assets/87182065/baa21560-3908-4626-864a-b6c564a8a02d)
Docker-imaget stopper på oppstart (windows hjemmemaskin).
Tekst:` "Image may have poor performance, or fail, if run via emulation"`
